### ISSUE TITLE
db.batch feature

### ISSUE THREAD

**Issue by hanumanjiblog** [G4brym/workers-qb#19]
Try to implement db.batch for all workers-qb operation.

await db.batch([
    db.prepare("UPDATE users SET name = ?1 WHERE id = ?2").bind( "John", 17 ),
    db.prepare("UPDATE users SET age = ?1 WHERE id = ?2").bind( 35, 19 ),
]);

**Comment by rupamking1** [comment]
db.batch is one of the most helpful feature of Cloudflare D1. Please try to add this feature in 🔥**workers-qb**🔥 package.

**Comment by luxint** [comment]
Hi, i was experimentng a little bit with workers-qb and i've patched my Databases.ts so that you can run commands  in batch like: 
`await qb.batch([
        qb.execute({query:'PRAGMA foreign_keys = 1'}),  
        qb.insert({tableName: 'testTable',
            data: [
                {my_field: 'test1',another: 123,},
                {my_field: 'test2',another: 456,},
                {my_field: 'test3',another: 789,},],
            returning: ['id', 'my_field'],
            onConflict: 'REPLACE',})])
`
Added the above as a test case as well and changed  the utils.ts to accomodate that.

See below for my Databases.ts, but mind you i'm just learning Typescript so bugs may galore and you have to attach the statements methods (.first(),.all() ...) to the 'normal' commands , couldn't really figure out how to  do that without changing the Builders.ts 


`import { QueryBuilder } from './Builder'
import { FetchTypes } from './enums'
import { Raw } from './tools'

export class D1QB extends QueryBuilder {
  private db: any

  constructor(db: any) {
    super()
    this.db = db
  }

  async execute(params: {
    query: string
    arguments?: (string | number | boolean | null | Raw)[]
    fetchType?: FetchTypes
  }): Promise<any> {
    return params

  }

  async batch(params:{
    query: string
    arguments?: (string | number | boolean | null | Raw)[]
    fetchType?: FetchTypes
  }[]): Promise<any>  {

    let batch:any[]=[]
    
    for (const row of params){
        let stmt = this.db.prepare(row.query)

        if (row.arguments) {
        const args = row.arguments.map((value) => {
            if (value instanceof Raw) {
            return value.content
            }
            return value
        })

        stmt = stmt.bind(...args)
        batch = batch.concat(stmt)
        }
    }

    if (batch.length == 1){

      if (params[0].fetchType === FetchTypes.ONE) {
        return batch[0].first()
      } else if (params[0].fetchType === FetchTypes.ALL) {
        return batch[0].all()
      }

      return batch[0].run()
    } 

    return this.db.batch(batch)  
  }    
}
`

**Comment by G4brym** [comment]
Hey there, we added support for db.batch in the latest release thanks to @ejyager00
You can see an [example here](https://workers-qb.massadas.com/databases/cloudflare-d1/#batch-queries)
