### ISSUE TITLE
Thanks and quick question about TIMESTAMP

### ISSUE THREAD

**Issue by osseonews** [G4brym/workers-qb#40]
Thanks for the amazing library. Much easier to use than any of the popular ORMs. Anyway, sorry for the noob question, but I see that when updating or inserting, you can use something like this:  created_at: new Raw("CURRENT_TIMESTAMP")

What is the underlying schema for a created_at or updated_at to use CURRENT_TIMESTAP? I was previously using something like this in D1: created_at INTEGER DEFAULT (cast(strftime('%s', 'now') as INTEGER)),

With the Raw, though, I'm not clear how it should be stored, as I don't see Timestamp as a data type in SQLite. Or is the CURRENT_TIMESTAMP only for postgres?

Thanks.

**Comment by G4brym** [comment]
`CURRENT_TIMESTAP` is an sqlite keyword that generates a string in this format `2024-04-05 14:56:59`
the appropriate datatype for it is `TEXT`, then you can do data operation [like this](https://www.sqlite.org/lang_datefunc.html)
On the other hand, if you prefer working with integers you can use the example you posted `strftime('%s', 'now')`
The helper `Raw('...')` is just a way to tell workers-qb to don't pass that value as a argument neither to wrap the value in quotes

For example, the code bellow would generate this query `insert into employees (updated_at, created_at) values ("CURRENT_TIMESTAMP", CURRENT_TIMESTAMP)`
```
const inserted = await qb
  .insert({
    tableName: 'employees',
    data: {
      updated_at 'CURRENT_TIMESTAMP',
      created_at: new Raw('CURRENT_TIMESTAMP'),
    },
  })
  .execute()
```

Notice the updated_at values is wrapped in quotes, this would insert the actual string CURRENT_TIMESTAMP in your table instead of a real date time `2024-04-05 14:56:59`

**Comment by osseonews** [comment]
Thanks for the quick reply. Didn't realize about SQLite keywords. thank you so much again for creating this library. Makes it really simple to interact with D1.
