### ISSUE TITLE
[Spike] Add interface for logging

### ISSUE THREAD

**Issue by aimproxy** [G4brym/workers-qb#51]
Hey, using this library on a side-project, and I can't stand the fact that there is no logging middleware on this library, every time I want to write a new query makes me shed a tear!

To improve debugging, we should introduce a logging interface similar to those used in other ORMs:

### Examples
- Sequelize https://sequelize.org/api/v7/interfaces/_sequelize_core.index.logging
- Prisma https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging
- Drizzle https://orm.drizzle.team/docs/goodies#logging

Thanks for considering this!

**Comment by G4brym** [comment]
Hey @aimproxy there is a hidden way to log queries, you just need to call the function `setDebugger(true)`, like this:
```ts
  const qb = new D1QB(env.DB);
  qb.setDebugger(true);
```
Then every time a query is executed, there will be a console.log with the sql query + parameters.

This is not documented, because at the time i needed something quick to debug an issue, but didn't quite like this interface, so i never wrote docs for it.

I will look at the examples you posted and try to improve this soon
Thanks 😄

**Comment by G4brym** [comment]
Hey there, i've just added a better logger in v1.5.0
Duration is available in `meta.duration` and your logger will always be called, even when the database throws an error
Here are the docs: https://workers-qb.massadas.com/utilities/#advanced-logger

**Comment by vickyRathee** [comment]
@G4brym thanks, that's awesome.
