### ISSUE TITLE
Multiple conditions in WHERE

### ISSUE THREAD

**Issue by repalash** [G4brym/workers-qb#64]
When adding multiple conditions to the WHERE, its possible to use operators within a condition, which interferes with other conditions which are not wrapped.

Example - 
```
new QuerybuilderTest().fetchAll({
        tableName: 'testTable',
        fields: '*',
        where: {
          conditions: ['field = ?1 OR test = ?2', 'test = ?3 OR field = ?4'],
          params: ['test', 123, 456, 'test'],
        },
      })
```
This generates the following - 
```SELECT * FROM testTable WHERE field = ?1 OR test = ?2 AND test = ?3 OR field = ?4```
which would always evaluate to false, as `test = ?2 AND test = ?3` will take precedence.

**Comment by G4brym** [comment]
Thanks @repalash, i've now published a new version with your fix

**Comment by repalash** [comment]
Thanks. workers-qb has a nice API. 
BTW Do you have any plans for a builder for sql expressions(where conditions etc)?

**Comment by G4brym** [comment]
Currently the only thing you can do is chain where conditions like this: https://workers-qb.massadas.com/modular-selects/
I have no plans to add a expression builder, right now, but if you have some api or library in mind, please share with me

I feel like, in order to add a good expression builder, i would also need to add some kind of models like drizzle, and that is already going into ORM territory
